# Makefile for DeepLAPI
# Auto-generated by swift-openapi-bootstrapper

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

# Shell settings: fail on error, pipefail
SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

# Swift Format Settings
SWIFT_FORMAT_OPTIONS := -i -p --ignore-unparsable-files --configuration .swift-format
SWIFT_FORMAT_TARGETS := ./Sources ./Tests

# Docker Settings
DOCKER_IMAGE := swift:latest

# Visuals
RED    := \033[31m
GREEN  := \033[32m
YELLOW := \033[33m
RESET  := \033[0m

# ------------------------------------------------------------------------------
# Meta Targets
# ------------------------------------------------------------------------------

.PHONY: all help check-clean merge-main format test-on-linux generate build test

# Default target runs help
all: help

# auto-doc: Parses comments starting with '##' to generate a help menu
help:
	@echo "$(YELLOW)Available commands:$(RESET)"
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  $(GREEN)%-20s$(RESET) %s\n", $$1, $$2}'

# ------------------------------------------------------------------------------
# Git Operations
# ------------------------------------------------------------------------------

check-clean: ## Check if there are uncommitted changes
	@echo "$(YELLOW)Checking for uncommitted changes...$(RESET)"
	@git diff-index --quiet HEAD -- || (echo "$(RED)Error: Uncommitted changes detected. Commit or stash them first.$(RESET)" && exit 1)
	@echo "$(GREEN)Clean.$(RESET)"

merge-main: check-clean ## Merge current branch into main and push
	$(eval BRANCH := $(shell git branch --show-current))
	@if [ "$(BRANCH)" == "main" ]; then \
		echo "$(RED)Error: You are already on main.$(RESET)"; \
		exit 1; \
	fi
	@echo "$(YELLOW)Merging $(BRANCH) into main...$(RESET)"
	git checkout main
	git pull origin main
	git merge "$(BRANCH)"
	git push origin main
	@echo "$(GREEN)Successfully merged $(BRANCH) into main and pushed.$(RESET)"
	@# Optional: switch back to the original branch
	@# git checkout "$(BRANCH)"

# ------------------------------------------------------------------------------
# Code Quality
# ------------------------------------------------------------------------------

format: check-clean ## Run swift-format on Sources and Tests
	@echo "$(YELLOW)Formatting Swift files...$(RESET)"
	@which swift-format > /dev/null || (echo "$(RED)swift-format not found.$(RESET)" && exit 1)
	@find $(SWIFT_FORMAT_TARGETS) -name "*.swift" -not -path "*/GeneratedSources/*" \
		| xargs swift-format $(SWIFT_FORMAT_OPTIONS)
	@git add .
	@echo "$(GREEN)Formatting complete. Changes staged.$(RESET)"

test-on-linux: ## Run swift tests inside a Docker container
	@echo "$(YELLOW)Running tests in Docker ($(DOCKER_IMAGE))...$(RESET)"
	docker run --rm \
		-v "$(CURDIR):/code" \
		-w /code \
		$(DOCKER_IMAGE) \
		swift test

build: ## Build the Swift package
	@echo "$(YELLOW)Building DeepLAPI...$(RESET)"
	swift build
	@echo "$(GREEN)Build complete!$(RESET)"

test: ## Run tests for the package
	@echo "$(YELLOW)Running tests for DeepLAPI...$(RESET)"
	swift test
	@echo "$(GREEN)Tests complete!$(RESET)"
